name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Dependencies (shared)
        run: pip install meson ninja==1.10.2.4
      - name: Dependencies (ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install -y valgrind && pip install numpy scipy
      - name: Build
        working-directory: .
        run: meson setup build && meson compile -C build
      - name: TestC
        working-directory: .
        run: meson test -C build
      - name: Valgrind
        if: contains(matrix.os, 'ubuntu')
        working-directory: .
        run: meson test -C build --wrap "valgrind --memcheck:leak-check=full --memcheck:show-leak-kinds=definite --memcheck:error-exitcode=1"
        shell: bash
      - name: TestPy
        if: contains(matrix.os, 'ubuntu')
        working-directory: ./py_wrapper
        run: python test_toric_code.py && python test_surface_code.py && python test_bb_codes.py
        shell: bash
